global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Options;
global using Microsoft.AspNetCore.Authorization;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Mapster;
global using MapsterMapper;
global using Scalar.AspNetCore;
global using FluentValidation;
global using SharpGrip.FluentValidation.AutoValidation.Mvc.Extensions;


global using ClinicAPI.Errors;
global using ClinicAPI.Abstractions;
global using ClinicAPI.Authentication;
global using ClinicAPI.Contracts.Polls;
global using ClinicAPI.Persistence;
global using ClinicAPI.Mapping;
global using ClinicAPI.Entities;
global using ClinicAPI.Services;
global using ClinicAPI.Contracts.Authentication;
global using ClinicAPI.Extensions;
global using ClinicAPI.Contracts.Results;
global using ClinicAPI.Authentication.Filters;
global using ClinicAPI.Abstractions.Consts;